export const FETCH_LIST_TASK = 'FETCH_LIST_TASK';
export const FETCH_LIST_FALIED = 'FETCH_LIST_TASK_FALIED';
export const FETCH_LIST_SUCCESS = 'FETCH_LIST_TASK_SUCCESS';
export const FILTER_TASK = 'FILTER_TASK';
